# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-24 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CctvWorldInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.CharField(default=0, max_length=50, verbose_name='新闻ID')),
                ('url', models.CharField(default='', max_length=500, verbose_name='地址链接')),
                ('title', models.CharField(default='', max_length=200, verbose_name='标题')),
                ('summary', models.TextField(default='', verbose_name='简介')),
                ('label', models.CharField(default='', max_length=50, verbose_name='标签')),
                ('from_news', models.CharField(default='CCTV', max_length=50, verbose_name='来源')),
                ('content', models.TextField(default='', verbose_name='内容')),
                ('release_time', models.CharField(default='0000-00-00 00:00:00', max_length=200)),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
        ),
    ]
