# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-24 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cctvworldinfo',
            name='front_image_url',
            field=models.CharField(default='', max_length=500, verbose_name='图片地址'),
        ),
    ]
