# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-27 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0002_cctvworldinfo_front_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cctvworldinfo',
            name='front_image_url',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='图片地址'),
        ),
    ]
