# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-28 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0003_auto_20180827_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='cctvworldinfo',
            name='content_image_url',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='内容图片地址'),
        ),
        migrations.AlterField(
            model_name='cctvworldinfo',
            name='front_image_url',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='列表图片地址'),
        ),
    ]
