# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-29 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0004_auto_20180828_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='TouTiaoNewsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.CharField(default=0, max_length=50, verbose_name='新闻ID')),
                ('url', models.CharField(default='', max_length=500, verbose_name='地址链接')),
                ('front_image_url', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='列表图片地址')),
                ('content_image_url', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='内容图片地址')),
                ('title', models.CharField(default='', max_length=200, verbose_name='标题')),
                ('label', models.CharField(default='', max_length=50, verbose_name='标签')),
                ('from_news', models.CharField(default='CCTV', max_length=50, verbose_name='来源')),
                ('content', models.TextField(default='', verbose_name='内容')),
                ('comment', models.IntegerField(default=0, verbose_name='评论数')),
                ('release_time', models.CharField(default='0000-00-00 00:00:00', max_length=200)),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
        ),
    ]
